### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/lutim_ynh#16]
Hello,
I can't install the app at all. The error is:

```
+ '[' '!' -e ../manifest.json ']'
++ sudo python3 -c 'import sys, json;print(json.load(open("../manifest.json"))['\''version'\''])'
Warning: Traceback (most recent call last):
Warning:   File "<string>", line 1, in <module>
Warning:   File "/usr/lib/python3.4/json/__init__.py", line 265, in load
Warning:     return loads(fp.read(),
Warning:   File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
Warning:     return codecs.ascii_decode(input, self.errors)[0]
Warning: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 213: ordinal not in range(128)
+ version=
Warning: !!
Warning:   lutim's script has encountered an error. Its execution was cancelled.
Warning: !!
```

Thanks

**Comment by maniackcrudelis** [comment]
Hi scith

I'm sorry, but I can't reproduce your error. On stable, testing or unstable, I can't reproduce.
This is an error with python, it try to read the manifest without utf-8. But I don't know why it does that !

This error happened here
https://github.com/YunoHost/yunohost/blob/testing/data/helpers.d/package#L118

**Comment by scith** [comment]
Hi, I'm closing the issue
Sorry but it was a problem on my server. I had no $LANG variable defined... I had to dpkg reconfigure the locales and edit ~/.profile
Thanks
