### ISSUE TITLE
install Failed DBD:SQLite error

### ISSUE THREAD

**Issue by ghost** [YunoHost-Apps/lutim_ynh#23]
Hi,

My install fails in processing installation carton dependances 
`! Installing DBD::SQLite failed. See /root/.cpanm/work/1521651916.26286/build.log for details. Retry with --force to force install it.
Successfully installed URI-Nested-0.10
Successfully installed URI-db-0.18
! Installing the dependencies failed: Installed version (1.44) of DBD::SQLite is not in range '1.50'`

My config : Debian jessie ARM and Yunohost 2.7

Thanks

**Comment by ldidry** [comment]
could you put the file `/root/.cpanm/work/1521651916.26286/build.log` somewhere on the web so I can view it? (please, don't paste it here, it will be too big)

**Comment by svnet-libre** [comment]
ok here is :
https://zero.svnet.fr/?b8dce1c889b5d401#1q+eAaUspEcAsbT7Iv/n3hkinVzLctJlF/mxJPiPa2E=

**Comment by ldidry** [comment]
Could you retry the installation? I just tried the installation and DBD::SQLite had no pb to be installed (I have other problems, but the build is fine).

Is your system up-to-date?

**Comment by svnet-libre** [comment]
Always the same problem in the same place.
And the system is up to date as well as "Carton" precisely

**Comment by ldidry** [comment]
As a workaround, I think you can install `libdbd-sqlite3-perl`, then retry the install: Carton should use the packaged version.

**Comment by svnet-libre** [comment]
`libdbd-sqlite3-perl` is already installed. But not `libdbd-sqlite3`
Now carton install works and Yunohst script install fail. Arf !! but I must have other missing dependencies.
finally I installed and configured lutim manually without yunohost and it works
