### ISSUE TITLE
Make lutim upload private, but images url public

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/lutim_ynh#32]
I have found issue #2 who seems to talk about this, but I can not find the conclusion inside or what to change in my instance to achieve this.

I would like that only my logged users can upload images on lutim, but that anybody can see uploaded images.

**Comment by maniackcrudelis** [comment]
That's actually the expected behavior for this app.
I updated the rules for SSOwat. It should now be fixed.
