### ISSUE TITLE
Instance statistics does not work

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/lutim_ynh#40]
On my instance, the SVG graphs of the stats page are empty.

It seems that I have a 404 error trying to get `/partial/raw.js` which is a graph library

**Comment by supermamie** [comment]
After comparing with https://lut.im/stats I noticed that even the HTML stats (Raw stats, at the bottom of the page) are empty on my instance, I just have the title, and no statistics.

**Comment by maniackcrudelis** [comment]
Looks like I have immediately a 404 on `/stats`on my own instance.

There's nothing specific into the nginx config about that. I don't know why it doesn't work anymore.
Maybe you could have a look to nginx logs to see if something happens.

**Comment by supermamie** [comment]
I found nothing in nginx logs (in fact, all nginx logs for this domain are empty, even access logs...)

**Comment by ldidry** [comment]
Do you have a cron task to generate the stats?
https://framagit.org/fiat-tux/hat-softwares/lutim/wikis/cron-jobs#statistics

**Comment by supermamie** [comment]
I ran the command manually and now I have statistics :+1: 
This should be setted-up by the install script, or at least notified in the documentation.

(for now I'll add a cron myself to update the stats every nights)
