### ISSUE TITLE
Use setting to store theme

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/lutim_ynh#49]
Hi, many thanks for this useful package!

I am using a different theme than the default lutim them: I downloaded it the `themes` folder and then modifier the lutim.conf file set the theme I wanna use.

When upgrading the package the folder in the `themes` directory remains but the config file is overwritten.

It would be nice if the theme was set through a setting in this app so that I can edit it (in CLI or something through a yunohost helper) and that is kept across upgrades/backups/restorations.

**Comment by maniackcrudelis** [comment]
You can turn off the overwriting of the config file into the config-panel.
That way, you can modify the file lutim.conf and not be bothered anymore when upgrading.

**Comment by nicofrand** [comment]
Oh? The app's config panel in yunohost, so `/yunohost/admin/#/apps/lutim`? Because I don't see anything.

**Comment by maniackcrudelis** [comment]
`/yunohost/admin/#/apps/lutim/config-panel`
That feature does not yet have a direct link into the admin panel.

**Comment by nicofrand** [comment]
:exploding_head: 

Thanks! I'll close this ticket then.
