### ISSUE TITLE
migration to 4.0 yunohost

### ISSUE THREAD

**Issue by boistordu** [YunoHost-Apps/lutim_ynh#50]
olimex lime 2 board

```
  - Aug 02 01:41:58 carton[30778]: ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0x9400080, needed 0x9380080)
  - Aug 02 01:41:58 systemd[1]: lutim.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by ldidry** [comment]
Note to maintainers of the package: this just need a remove of `local` directory then redo a `carton install` with the options previously used.

**Comment by grosbedos** [comment]
> Note to maintainers of the package: this just need a remove of `local` directory then redo a `carton install` with the options previously used.
@ldidry , can you explain how can i get rid off this error please ? (manually)

Best regards

**Comment by ldidry** [comment]
In the folder of Lstu:
```
rm -rf local
carton install --without=test
```

**Comment by grosbedos** [comment]
Thanks a lot ;)
You saved my day !

**Comment by boistordu** [comment]
still there are some errors during compilation:
! Configure failed for Socket6-0.29. See /root/.cpanm/work/1596762030.23271/build.log for details.
! Configure failed for NetAddr-IP-4.079. See /root/.cpanm/work/1596762030.23271/build.log for details.

**Comment by ldidry** [comment]
It happens sometimes. You can try this workaround (do it in Lutim install directory):

```
cpanm -L local Socket6 NetAddr::IP
```

If it does not work, please post relevant log (`/root/.cpanm/work/1596762030.23271/build.log`), please.

**Comment by boistordu** [comment]
@ldidry good it worked after I relaunched the app through systemd
